//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSync.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Data_account {
            get {
                return ((string)(this["Data_account"]));
            }
            set {
                this["Data_account"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rKSW7LpXOM8n4ZEQc9FnQTLbpgtQ9qUY4HP3mQkGZJFHNEamt9yI?6Dy?5zjlvp0vSwAfq3E4BxAHB!Sm" +
            "nAggocCw181vqHnNBu1a8d9drAqzmcnGKYvI4?MIzPY8XJjGOywc=489KFcwgfMl2cWSQ5uboyRjrkrm" +
            "ryeq0DFcFByp0rKObROT1X!i-Nkb7Dgf/fOTiXEeJAWohAQVpi6IiqkG?NtkIc/wWjLv0MLYJ9c6kf7G" +
            "WXbXjWNULdfoh/s8XCzI6HlT0fIo3G=q1kA3QuGt1QLIfMZxdAOebGji745HEee/rPes6J0?!TvvG-b4" +
            "RKD11s?dbos4E7SQCOuNo1Q=!DemHroUhfAs7tV128SQIZY1bc3XYvjkKz8B6dk9v67vXJ3X7dylwp0j" +
            "rchwSQH!Hs?Czg!DLYJnm7LkrcszDOUPNDIQ2u7UEA-Su7RvlgvGlnE79PulDoBq!JAda-YFVOnEABgY" +
            "6sVWr29rG-OJsLfQ20mby0qaxCRPRj?sy!EqUMyBzmD86ILOow=LLfzc?4?E=YVd?dZCV9pQvOvZX!=D" +
            "fY1JVhxtbQ37t8fsA5a6VKIov2RWGTKWu3COe07jUcN9v-FBbbSPT-6rCkl3IR7wgAJ3pTfI0/lAewpP" +
            "e7PV/CXfqS0FbBVZmD/fQ7?oljo-tgpdCLfM/FOn!WgnyVrIybqt/JSl0psmrvN48HDmRoCpRtKH1xJl" +
            "Pzg21p-j5ehvGgJpBsgJC=Tw5ImKqHqgCSBvaqknSzmyk?akxt9NBXEHRAfhQjZFT/BEpFAvi5!GI7!G" +
            "2E93dQ6UV0ueROYYx//sYUKkPPLs-EnG4y/!Bpk-6=Tz1LmOReUL8-MmOOC224gHNdr2bBNJt0/NXOtx" +
            "FsRdhuDw!wzUzCY!jdxdqEkI8KwPbuZzHpe2Xtr6/e!8aCq?M9Wx/hzi-RmOAoDLmpBnPCXErm/vN4!D" +
            "XgFGpCD98=IWWMdHk7xPSVkWHkvaTD6ao0DZcB5=An!M1p/F9a8N9/rUweb6yAc!d2p0h=?1LgxgAsZS" +
            "/c8oD3fGPg8=AVDWR?tFta-Mh0jVff9PYSQ3ZBAJdHzs8nKCKaNtHZTZmVV6APXkOMJRFgl7?wiL3bjt" +
            "bGGa8pJuMJGpTOQxt7p-8ZFM=j/y48zcdBY9PIGpz166oZFt=APcIcO-QnFm2EtbtYdHIlBUKPd?Ug2D" +
            "ocLiBJ5qL3ehlH87QbAe=zYrAwwaNAO-Zzn99!Z=Aw19EPT!JRwHCD6Gw4o7h7FsV2NotpVHrbcud6UQ" +
            "ByQ8MfTh3nvRCwrBOt-aJE?zD7ivs6nK-9c=8Y3zC8TR9j3fR2!Ay?D-EaZQMRvEYtG5P8ZBVRWGfuvc" +
            "5/ptK1AC3wipU/=mnK=b6vH8X3Gq5n0y6vcxn2s-IPL7YR3V-Q?9A7iyW7bYlp!cmkH4vZi=8JSXpk2Q" +
            "9XFoOfXj1oc5jIiMYfKQ12lV=fTWRHGzKFqRcadzg-QUrXjcLiQky//?GFagZ5/ih26EiTtrWF!grcbv" +
            "79XoG7UVN6ZEmbfdPXxwSKyFs80M10yWBsBkI2phsR72HwCw7RecLNIvK7lI-=l9IJGv1=TMOZpse9qT" +
            "GO?XSE!tuGa3jOA1xR=uR5bm8KuHG1USnt?yTOjV4NMpz-NBr/mFHIhHfBW/3p198i=9PD5IzCevXpHy" +
            "OVeDZPlYbo7lIzleVNX3tufY9WeUV-JC/GHAfSVgtpPgfHYVKFD9bJmkbQsj10B2l6pk!5Ta5cXNBhsS" +
            "uVFllyzn86qPrf9sR66lAPHC1uBEt/DiuJ0yV01cKqFCWgSVK-8v6FzTAGiRY2cUgv=yfRLIt0P!crun" +
            "lsHMvS3vAx11OATDkyuLIEyGt7fxe7h!mWAvd0jsQxCPRSt/?wLl9/W3-LXuca3yc7nPojTYe?W?TL!Q" +
            "HfFv42ADQ9S1hud1i1BPDaVCYqUOrxkaSsw=OG75W3dNYdwdBHMZMsGBVwc=4DeItW0P8Ve6TYo1y!I0" +
            "4r6eVlRlptt3!EXcYqOoWKPrl0xznLEehnh7Kiho-64qTwe")]
        public string API_TOKEN {
            get {
                return ((string)(this["API_TOKEN"]));
            }
        }
    }
}
